env: standard
runtime: nodejs18
instance_class: F1
inbound_services:
  - warmup
handlers:
  - url: /.*
    secure: always
    script: auto
env_variables:
  GOOGLE_MAPS_API_KEY: AIzaSyAFsmGJ3zKXg9v2-rYAUKQiDTfl7Cl0KnY
